### ISSUE TITLE
Form elements/style

### ISSUE THREAD

**Issue by iholler** [iholler/crows#1]
Thinking we should just port in some bootstrap elements to keep me from obsessing over the visuals. Help keep me focused on the .js, but bootstrap has it's on set of problems that come along with it in regard to forms...

**Comment by voltron33** [comment]
Since we will want this to be plug and play I think we should leave the layout and styling as vanilla as possible. Including bootstrap in a final live version may be good just to show it off but for the initial release my vote is that we just leave things as is for now.

**Comment by iholler** [comment]
Agreed. I figured that once the project is up and running we'll strip the project of everything but the js (and maybe the php to plugin to a mysql database). With that said, I'm on the same page with you.
